# Generated by Django 3.0.4 on 2020-03-25 16:32

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=43)),
            ],
        ),
    ]
