# Generated by Django 3.0.4 on 2020-03-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
