# Generated by Django 3.0.5 on 2020-05-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200505_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttributeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=180)),
            ],
        ),
    ]
