# Generated by Django 3.0.5 on 2020-05-15 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200514_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='category_desc',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
