# Generated by Django 3.0.5 on 2020-06-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_productcategory_category_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantSizeOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
    ]
