# Generated by Django 3.0.5 on 2020-06-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_userproductvariantcart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductvariantcart',
            name='size',
        ),
    ]
