# Generated by Django 3.0.5 on 2020-06-25 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_userproductvariantcart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductvariantcart',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.ProductVariantSize'),
        ),
    ]
