# Generated by Django 3.0.5 on 2020-06-28 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_auto_20200625_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproductvariantcart',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.ProductVariantSize'),
        ),
    ]
